name: Validation of cicd_example
on: [push]

jobs:
  run-all:
    runs-on: windows-latest
    name: Run MSBuild
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        id: checkout_code
            
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v2
        id: setup_msbuild
              
      - name: Run MSBuild
        id: run_msbuild
        run: msbuild .\cicd_example.sln /p:Configuration=Debug

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: cicd_example_binary  # Artifact name
          path: ./cicd_example/bin/Debug/cicd_example.exe   # Files or folder to upload
          
