name: Validation of Console App
on: [push]
jobs:
  run-selected-unittests:
    runs-on: self-hosted
    name: Run MSBuild and VSTest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2
        id: checkout_code
            
      - name: Setup MSBuild and add to PATH
        uses: microsoft/setup-msbuild@v2
        id: setup_msbuild
              
      - name: Run MSBuild
        id: run_msbuild
        run: msbuild .\cicd_example.sln /p:Configuration=Debug
#          nuget restore .\cicd_example.sln
#          msbuild .\cicd_example.sln  /t:build /p:Configuration=Debug- name: Setup VSTest and add 
#                   to PATH
#        uses: darenm/Setup-VSTest@v1
#        id: setup_vstest- name: Test Case Workers
#        id: run_vstest
#        working-directory: UnitTests\bin\Debug
#        run: vstest.console.exe .\UnitTests.dll /Tests:TestCaseWorkerIds,TestCaseWorkersCount


      - name: Upload Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output  # Artifact name
          path: ./cicd_example/bin/Debug/cicd_example.exe        # Files or folder to upload
          
      - name: Show Directory
        run: dir